services:
  unitedgram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unitedgram
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./avatar_cache.json:/app/avatar_cache.json
      - ./cookies:/app/cookies
    command: ["python", "main.py"]